### ISSUE TITLE
unable to set myst-parser to 0.13 on GH actions

### ISSUE THREAD

**Issue by firasm** [firasm/template_jb_syllabus#6]
There is a strange error when I add `myst-parser~=0.13` to the requirements.txt.

Here is the traceback:

```
Run pip install -r requirements.txt
7
Collecting jupyter-book
8
  Downloading jupyter_book-0.9.1-py3-none-any.whl (47 kB)
9
Requirement already satisfied: setuptools in /opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages (from jupyter-book->-r requirements.txt (line 2)) (49.2.1)
10
Collecting matplotlib
11
  Downloading matplotlib-3.3.3-cp38-cp38-manylinux1_x86_64.whl (11.6 MB)
12
Collecting myst-parser~=0.13
13
  Downloading myst_parser-0.13.1-py3-none-any.whl (36 kB)
14
Collecting numpy
15
  Downloading numpy-1.19.5-cp38-cp38-manylinux2010_x86_64.whl (14.9 MB)
16
Collecting click
17
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
18
Collecting cycler>=0.10
19
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
20
Collecting docutils>=0.15
21
  Downloading docutils-0.16-py2.py3-none-any.whl (548 kB)
22
Collecting jinja2
23
  Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
24
Collecting jsonschema
25
  Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
26
Requirement already satisfied: setuptools in /opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages (from jupyter-book->-r requirements.txt (line 2)) (49.2.1)
27
Collecting attrs>=17.4.0
28
  Downloading attrs-20.3.0-py2.py3-none-any.whl (49 kB)
29
Collecting kiwisolver>=1.0.1
30
  Downloading kiwisolver-1.3.1-cp38-cp38-manylinux1_x86_64.whl (1.2 MB)
31
Collecting markdown-it-py~=0.6.0
32
  Downloading markdown_it_py-0.6.1-py3-none-any.whl (81 kB)
33
Collecting MarkupSafe>=0.23
34
  Downloading MarkupSafe-1.1.1-cp38-cp38-manylinux1_x86_64.whl (32 kB)
35
Collecting mdit-py-plugins~=0.2.4
36
  Downloading mdit_py_plugins-0.2.4-py3-none-any.whl (39 kB)
37
Collecting myst-nb~=0.10.1
38
  Downloading myst_nb-0.10.1-py3-none-any.whl (36 kB)
39
INFO: pip is looking at multiple versions of mdit-py-plugins to determine which version is compatible with other requirements. This could take a while.
40
INFO: pip is looking at multiple versions of markupsafe to determine which version is compatible with other requirements. This could take a while.
41
Collecting MarkupSafe>=0.23
42
  Downloading MarkupSafe-1.1.0.tar.gz (18 kB)
43
  Downloading MarkupSafe-1.0.tar.gz (14 kB)
44
    ERROR: Command errored out with exit status 1:
45
     command: /opt/hostedtoolcache/Python/3.8.6/x64/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qeupcy8p/markupsafe_a57661f07b7c4f9fb67f154a74ae1402/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qeupcy8p/markupsafe_a57661f07b7c4f9fb67f154a74ae1402/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-g2vx2dkl
46
         cwd: /tmp/pip-install-qeupcy8p/markupsafe_a57661f07b7c4f9fb67f154a74ae1402/
47
    Complete output (5 lines):
48
    Traceback (most recent call last):
49
      File "<string>", line 1, in <module>
50
      File "/tmp/pip-install-qeupcy8p/markupsafe_a57661f07b7c4f9fb67f154a74ae1402/setup.py", line 6, in <module>
51
        from setuptools import setup, Extension, Feature
52
    ImportError: cannot import name 'Feature' from 'setuptools' (/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/setuptools/__init__.py)
53
    ----------------------------------------
54
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
55
WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
56
You should consider upgrading via the '/opt/hostedtoolcache/Python/3.8.6/x64/bin/python -m pip install --upgrade pip' command.
57
Error: Process completed with exit code 1.
```

**Comment by firasm** [comment]
fixed in e7da1a9
